stages:
  - test
  - docker
  - staging

test:
  image: nextbillionai/nbroutes-test:20201014
  stage: test
  script:
    - cargo test

docker:
  image: asia-southeast1-docker.pkg.dev/nextbillion/internal/nip:1.0.3
  stage: publish
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - set -e
    - nip -t gateway-keys:$CI_COMMIT_TAG .
  only:
    - tags