name: test
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: run
        run: |
          #!/bin/bash
          set -e
          cargo test
